local usr_command = vim.api.nvim_create_user_command

usr_command('ReplToggle', function()
  require('display').toggle_repl()
end, {})
usr_command('ReplOpen', function()
  require('display').open_repl()
end, {})
usr_command('ReplClose', function()
  require('display').close_repl()
end, {})
usr_command('ReplRestart', function()
  require('display').close_repl()
  require('display').open_repl()
end, {})

usr_command('ReplSendLine', function()
  require('interaction').send_line()
end, {})
usr_command('ReplSendFile', function()
  require('interaction').send_file()
end, {})
usr_command('ReplSendParagraph', function()
  require('interaction').send_paragraph()
end, {})
usr_command('ReplSendSelection', function()
  require('interaction').send_selection()
end, {})

vim.keymap.set('n', '<leader>rt', '<cmd>ReplToggle<CR>')
vim.keymap.set('n', '<leader>ro', '<cmd>ReplOpen<CR>')
vim.keymap.set('n', '<leader>rc', '<cmd>ReplClose<CR>')
vim.keymap.set('n', '<leader>rr', '<cmd>ReplRestart<CR>')

vim.keymap.set('n', '<leader>rl', '<cmd>ReplSendLine<CR>')
vim.keymap.set('n', '<leader>rf', '<cmd>ReplSendFile<CR>')
vim.keymap.set('n', '<leader>rp', '<cmd>ReplSendParagraph<CR>')
vim.keymap.set('v', '<leader>rs', '<cmd>ReplSendSelection<CR>')
